# Generated by Django 4.2.6 on 2023-11-08 06:26

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=100)),
                ('male', models.CharField(choices=[(0, 'М'), (1, 'Ж')], max_length=50)),
                ('databirth', models.CharField(max_length=50)),
                ('diagnose', models.CharField(max_length=50)),
                ('features', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=15)),
                ('palata', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=15)),
                ('rest', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_in', models.CharField(max_length=15)),
                ('room', models.CharField(max_length=15)),
                ('phone_room', models.CharField(max_length=15)),
                ('data_out', models.CharField(max_length=15)),
                ('reason', models.CharField(max_length=15)),
                ('patient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.record')),
            ],
        ),
    ]
