# Generated by Django 5.0 on 2023-12-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_withageandmale_withdate_withpatient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Название')),
                ('limit', models.FloatField(verbose_name='Лимит средств')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Название')),
                ('sum', models.FloatField(verbose_name='Сумма')),
                ('time', models.DateField(verbose_name='Дата начисления')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.FloatField(verbose_name='Сумма транзакции')),
                ('time', models.DateTimeField(verbose_name='Дата и время')),
                ('category', models.CharField(max_length=35, verbose_name='Категория бюджета')),
            ],
        ),
    ]
