# Generated by Django 5.0 on 2023-12-19 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_ordinaryuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='sum',
            new_name='summ',
        ),
    ]
