# Generated by Django 5.0 on 2023-12-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_sum_transaction_summ'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='summ',
            new_name='sum',
        ),
    ]
